coverage:
  precision: 2
  round: down
  range: "50...90"

  status:
    project:
      default:
        target: 90
        threshold: 10
        informational: true
    patch:
      default:
        target: 90
        threshold: 10
        informational: true
    changes: no
