language: node_js
node_js:
    - "10"
services:
  - docker
stages:
  - test
  - name: documentation
    if: branch = master
  - name: build
  - branch = master OR branch = develop OR type = pull_request
jobs:
  include:
    - script: npm run lint
    - script: npm run test
    - script: npm run codecov
    - stage: documentation
      script: npm run docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: ./docs
        target_branch: gh-pages
        on:
          branch: master
    - stage: build
      script: docker build -t $TRAVIS_REPO_SLUG/v$TRAVIS_BUILD_NUMBER .
