version: '3.7'

services:
  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - "mongo_data:/data/db/"

  node:
    build: 
      context: .
      target: base 
    environment: 
      DB_HOSTNAME: 
      DB_PORT:
      DB_DATABASE: 
      DB_USERNAME:
      DB_PASSWORD:
      NODE_ENV:
      SERVER_PORT: 
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ".:/node:rw"
    command: ["npm", "run", "start"]
    depends_on:
      - "mongo"

volumes:
  mongo_data:
