---
# Use systemd to keep the app running
- name: Create app service
  template:
    src: systemd.j2
    dest: /etc/systemd/system/{{ application_name }}.service
    owner: root
    group: root
    mode: 0664

- name: start and enable app
  service:
    name: "{{ application_name }}"
    state: started
    enabled: true

# proxy the output to port 80 (guest), which vagrant is mapping to port 8080 on
# the host.

- name: Create nginx proxy
  template:
    src: nginx.j2
    dest: /etc/nginx/conf.d/{{application_hostname}}.conf
    owner: root
    group: root
    mode: 0755
  register: nginx_config

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true
  register: nginx_running
  when: nginx_config.changed

- name: restart nginx if needed
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed and not nginx_running.changed
