---
  # first we need to move our code into the appropriate directory on the remote
- name: Sync code to server
  synchronize:
    src: "../../../../"
    dest: "{{ application_root }}"
    delete: yes
    rsync_path: "sudo -u {{application_name}} rsync"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.nyc_output"
      - "--exclude=.vagrant"
      - "--exclude=ansible"
      - "--exclude=build"
      - "--exclude=coverage"
      - "--exclude=docs"
      - "--exclude=node_modules"
      - "--exclude=package-lock.json"
      - "--exclude=src/server/config.js"
  register: code_updated


- set_fact:
    app_restart_needed: true
  when: code_updated.changed
