---
# Create the project database and a user collection, if they don't already exist
- name: Check if database already exists
  shell: /bin/mongo {{mongo_url}}/{{mongo_database}} --eval 'db.getUsers()' {{mongo_database}}
  failed_when: false
  changed_when: false
  register: db_users

# Add the database for the application, along with a user account for the app
- name: create app database and user account
  mongodb_user:
    database: "{{mongo_database}}"
    name: "{{mongo_username}}"
    password: "{{mongo_password}}"
    login_user: "{{ application_name }}"
    login_password: None
    state: present
    roles: readWrite
  when: mongo_username not in db_users.stdout

- name: Check if QA User already exists
  shell: /bin/mongo {{mongo_url}}/{{mongo_database}} --eval 'db.users.find()'
  failed_when: false
  changed_when: false
  register: qa_user

# Create the users collection for the application, which will allow for mocking
# CAS access
- name: Add Users Collection
  shell: /bin/mongo {{mongo_url}}/{{mongo_database}} --eval {{create_user|quote}}
  when: qa_user_huid not in qa_user.stdout
