---
- name: Server Config
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - server_config

- name: Copy Code
  hosts: vagrant
  become: yes
  become_method: sudo
  roles:
    - copy_code

- name: Mongo Install
  hosts: vagrant
  become: yes
  become_method: sudo
  roles:
    - mongo_install

- name: Mongo Config
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - mongo_config

- name: Deploy App
  hosts: all
  become: yes
  become_user: "{{ application_name }}"
  roles:
    - node_config
    - build_app

- name: Server Config
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - launch_app
