---
- name: Server Config
  hosts: vagrant
  become: yes
  become_method: sudo
  roles:
    - server_config
    - mongo_config
    - copy_code

- name: Deploy App
  hosts: vagrant
  become: yes
  become_user: "{{ application_name }}"
  roles:
    - node_config
    - build_app

- name: Server Config
  hosts: vagrant
  become: yes
  become_method: sudo
  roles:
    - launch_app
