name: Increment Version
on:
  push:
    branches:
      - main
      - develop
jobs:
  update_version:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: update minor 
        if: github.ref == 'refs/heads/main'
        run: echo "SEMVER_LEVEL=minor" >> $GITHUB_ENV
      - name: update patch 
        if: github.ref == 'refs/heads/develop'
        run: echo "SEMVER_LEVEL=patch" >> $GITHUB_ENV
      - run: |
          git config --local user.name "SEAS COMPUTING ROBOT"
          git config --local user.email "computing-dev-team@seas.harvard.edu"
          git config --local push.default matching
          git config credential.helper "store --file=.git/credentials"
          echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
          git checkout -- .
          npm version ${{ env.SEMVER_LEVEL }} -m "Automatic bump to %s"
          git push --tags origin ${{ github.ref }}
