name: Documentation 
on: 
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" 
    branches: 
      - main
jobs:
  test:
    name: Generate Documentation 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 10
      - run: npm run docs:generate
      - run: npm run docs:publish
