name: Documentation 
on: 
  workflow_run:
    workflows:
      - Increment Version
    branches: 
      - main
    types:
      - completed
jobs:
  test:
    name: Generate Documentation 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 10
      - run: |
          git config --local user.name "SEAS COMPUTING ROBOT"
          git config --local user.email "computing-dev-team@seas.harvard.edu"
          git config credential.helper "store --file=.git/credentials"
          echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
          npm ci 
          npm run docs:generate
          npm run docs:publish
