name: Docker Container 
on: 
  workflow_run:
    workflows:
      - Increment Version
    branches:
      - main
      - develop
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          depth: 0
      - name: version
        run: echo "VERSION_TAG=$(git tag | tail -n1)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.VERSION_TAG }}
      - name: docker-version
        run: |
          echo "DOCKER_TAG=$(if (git branch --points-at HEAD | grep main); then echo stable; else echo qa; fi)" >> $GITHUB_ENV
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ env.DOCKER_TAG }}
          tag_with_ref: true
