name: Docker Container 
on: 
  release:
    types: 
      - published
    branches:
      - main
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: stable
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_TAG=stable" >> $GITHUB_ENV
      - name: qa 
        if: github.ref == 'refs/heads/develop'
        run: echo "DOCKER_TAG=qa" >> $GITHUB_ENV
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ DOCKER_TAG }}
          tag_with_ref: true
