name: Publish Docker Image
on: 
  workflow_run:
    workflows:
      - Increment Version
    branches:
      - main
      - develop
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find latest version
        run: echo "VERSION_TAG=$(git tag -l v* | tail -n1)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.VERSION_TAG }}
      - name: docker-version
        run: |
          echo "DOCKER_TAG=$(if (git branch --points-at HEAD | grep main); then echo stable; else echo qa; fi)" >> $GITHUB_ENV
      - name: qemu
        uses: docker/setup-qemu-action@v1
      - name: buildx
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Publish image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}
            ghcr.io/${{ github.repository }}:${{ env.VERSION_TAG }}
